![title](imagens/M07-ObtendoDados02.jpg)

# Obtendo Dados - Parte 2

Nesta parte específica do curso, vamos ver como podemos fazer a importação de dados.

No mundo real, os dados estão dispersos e em vários formatos: **txt, csv, excel, json, zip, etc.**

Nesta sessão, vamos ver como podemos fazer a importação de dados de diversos formatos para o *Pandas*.

### Importando Dados no formato Texto (.txt)

A forma mais simples de dados que vamos trabalhar são os **arquivos .txt**. Para importar dados de texto, precisamos de um conjunto de dados neste formato. 

A título de exemplo, vamos importar um conjunto de dados do mundo real. Vamos utilizar os dados do índice de preços ao consumidor obtidos no site do Departamento do Trabalho dos EUA. Você pode baixar os dados clicando no seguinte link: [Departamento do Trabalho dos EUA: indice de preço ao consumidor](https://download.bls.gov/pub/time.series/ap/ap.data.0.Current). 

O arquivo estará disponível como recurso dessa aula (*dados_txt.txt*)

In [1]:
# Importando o Pandas
import pandas as pd
# verificando a versão
pd.__version__

'2.2.2'

In [2]:
# Importando os dados do arquivo txt.
dados = pd.read_table('dataset/dados_txt.txt')
dados.head()

   series_id          year period         value  footnote_codes
0  APU0000701111      1995    M01         0.238             NaN
1  APU0000701111      1995    M02         0.242             NaN
2  APU0000701111      1995    M03         0.242             NaN
3  APU0000701111      1995    M04         0.236             NaN
4  APU0000701111      1995    M05         0.244             NaN

In [3]:
# verificando o tipo de dados importado
type(dados)

pandas.core.frame.DataFrame

In [4]:
# Podemos, por exemplo, fazer a importação apenas de determinadas colunas.
dados = pd.read_table('dataset/dados_txt.txt', usecols = ['year', 'period'])
dados.head()

   year period
0  1995    M01
1  1995    M02
2  1995    M03
3  1995    M04
4  1995    M05

### Importando Dados no formato CSV (Valores Separados por Vírgula)
CSV ou valores separados por vírgula é um dos formatos mais utilizados para salvar dados. Você verá que a maioria dos conjuntos de dados disponíveis publicamente para análise/aprendizado de máquina está no formato .csv. 

No próximo exemplo, vamos utilizar dados de crime para analisar os incidentes criminais ocorridos na cidade de Chicago. 

Você pode baixar esses dados clicando no link a seguir: [Incidentes Criminais ocorridos na cidade de Chicago-USA de 2001 até a presente data](https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.csv?accessType=DOWNLOAD). O arquivo estará disponível como recurso dessa aula (dados_csv.csv)

In [5]:
# Importando o arquivo CSV utilizando a função read_csv()
dados = pd.read_csv('dataset/dados_csv.csv')
dados.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"

In [6]:
dados.shape

(7761616, 22)

### Importando Dados do Excel
Arquivos em Excel é um outro formato muito utilizado na área de Ciência de Dados. Você pode usar a função pandas **read_excel()** com seu argumento sheet_name para ler os dados de uma planilha específica de dados do Excel. 

Para demostrar a importação de dados no formato Excel, vamos utilizar uma planilha **Superstore Excel** com três guias - Pedidos, Devoluções, Pessoas, que você pode baixar clicando no seguinte link: [Planilha Superstore - Excel](https://community.tableau.com/s/question/0D54T00000CWeX8SAL/sample-superstore-sales-excelxls). 

Essa planilha estará disponível como recurso dessa aula (dados_excel.xls).

In [9]:
! pip install xlrd==2.0.1

Collecting xlrd==2.0.1
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [10]:
# Importando o arquivo EXCEL utilizando a função read_excel()
dados = pd.read_excel('dataset/dados_excel.xls')
dados.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [11]:
# Convertendo o DataFrame acima para JSON e salvando em um arquivo 
dados.to_json("dataset/dados_json.json", orient='columns')

### Importando Dados em JSON (Java Script Notation)
O formato JSON é a forma preferida de troca de dados no mundo das APIs. Para lidar com dados estruturados JSON, você pode usar a função pandas **read_json()** para ler os argumentos e dados de um arquivo nesse formato.

Para tanto, vamos utilizar os mesmos dados que utilizamos para importação de dados no formato do Excel (Planilha: SuperStore), que salvamos no formato Json.

Esse arquivo estará disponível como recurso dessa aula (dados_json.json)

In [12]:
# Importando o arquivo no formato JSON utilizando a função read_json()
dados = pd.read_json('dataset/dados_json.json', orient='columns')
dados.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,1478563200000,1478822400000,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,1478563200000,1478822400000,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,1465689600000,1466035200000,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,1444521600000,1445126400000,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,1444521600000,1445126400000,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Importanto Dados Pickled (Serializados)
Qualquer objeto em Python pode ser serializado para que possa ser salvo no disco. **O processo de serialização é conhecido como "pickle"**. Portanto, *"Pickling"* é o processo pelo qual uma hierarquia de objetos Python é convertida em um fluxo de bytes. E *"Unpickling"* é a operação inversa, em que um fluxo de bytes (de um arquivo binário ou objeto byte ou similar) é convertido de volta em uma hierarquia de objetos. Esse processo também é conhecido como serialização ou achatamento ("flattening").

A ideia é que esse fluxo de caracteres contenha todas as informações necessárias para reconstruir o objeto em outro script Python. Quando você trabalhar com aprendizado de máquina, precisará treinar seu modelo várias vezes, e a serialização ajudará você a economizar tempo de treinamento. Depois de selecionar seu modelo treinado, você pode compartilhar esse modelo treinado com outras pessoas; eles não precisam perder tempo com o retreinamento do modelo. Abordaremos essa parte mais tarde.

Vamos aprender a ler um arquivo em Pickled (serializado). Para tanto, você pode utilizar a função Pandas: read_pickle.
Para tanto, vamos utilizar um arquivo serializado do Famoso DataSet Mnist (que possui imagens 28x28x1 de números escritos a mão). Você pode baixar esse arquivo em: [Kaggle - Mnist Pickled](https://www.kaggle.com/datasets/pablotab/mnistpklgz?resource=download).

Este arquivo arquivo estará disponível como recurso dessa aula (mnist.pkl)

In [13]:
# Importando um arquivo serializado (Pickled)
dados = pd.read_pickle('dataset/mnist.pkl')
print("Tipo de dados: ", type(dados))
for indice, digitos in enumerate(dados):
    print(indice, ":", digitos)

Tipo de dados:  <class 'tuple'>
0 : (array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32), array([5, 0, 4, ..., 8, 4, 8], dtype=int64))
1 : (array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32), array([3, 8, 6, ..., 5, 6, 8], dtype=int64))
2 : (array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32), array([7, 2, 1, ..., 4, 5, 6], dtype=int64))

### Importando dados comprimidos (ZIP)
O formato de arquivo ZIP é um padrão comum de compactação e arquivamento. O processo de compactação é utilizado para reduzir o espaço de armazenamento e também poder realizar as transferências de arquivos mais rapidamente.

Assim, como você pode descompactar um arquivo para poder ler os dados? Em linguagem Python existe um módulo "zipfile" que fornece ferramentas para criar, ler, escrever, anexar e listar um arquivo ZIP. 

Para exemplificar, descompactaremos dados de solo da região africana que você vai encontrar como recurso dessa aula (africa_soil_train.zip)

In [14]:
# Importanto o Módulo ZIPFILE
import zipfile as zip

In [15]:
dataset = "dataset/africa_soil_train.zip"
with zip.ZipFile(dataset, "r") as z:
    z.extractall()

Neste exemplo, o arquivo extraido ficará no diretório corrente. O nome do arquivo é training.csv. 

Uma vez extraido, basta realizar a importação de um arquivo CSV.

### Fim