![title](imagens/cabec_08g.jpg)

# <font color='green'>Projeto 6 - Marketing para Instituições Financeiras - Parte 04</font>
## <font color='green'>Tratamento de Valores Ausentes - B</font>

## Carregando os Pacotes e o DataSet

In [1]:
# Importação dos Pacotes necessários para este projeto
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Carrega o dataset
df = pd.read_csv("dados/bank-full_parte3.csv")

In [3]:
# Shape
df.shape

(45211, 19)

In [4]:
# Amostra
df.head()

,Unnamed: 0,age,job,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,0,58,management,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,1,44,technician,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,2,33,entrepreneur,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,3,47,blue-collar,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,4,33,unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [5]:
# Como removemos o id, ao sarvar o arquivo, o pandas cria uma nova coluna de identificação e ele chama de Unnamed:0 
# Vamos removê-la.
df.drop(["Unnamed: 0"], axis = 1, inplace = True)

In [6]:
# Amostra
df.head()

,age,job,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,58,management,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,44,technician,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,33,entrepreneur,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,47,blue-collar,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,33,unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [7]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   salary     45180 non-null  float64
 3   balance    45211 non-null  int64
 4   default    45211 non-null  object
 5   housing    45211 non-null  object
 6   loan       45211 non-null  object
 7   contact    45211 non-null  object
 8   day        45211 non-null  int64
 9   month      45188 non-null  object
 10  duration   45211 non-null  int64
 11  campaign   45211 non-null  int64
 12  pdays      45211 non-null  int64
 13  previous   45211 non-null  int64
 14  poutcome   45211 non-null  object
 15  target     45204 non-null  object
 16  marital    45211 non-null  object
 17  education  45211 non-null  object
dtypes: float64(1), int64(7), object(10)
memory usage: 6.2+ MB

In [8]:
# Temos valores nulos?
df.isna().any()

age          False
job          False
salary        True
balance      False
default      False
housing      False
loan         False
contact      False
day          False
month         True
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
target        True
marital      False
education    False
dtype: bool

In [9]:
# Temos valores nulos?
df.isna().sum()

age           0
job           0
salary       31
balance       0
default       0
housing       0
loan          0
contact       0
day           0
month        23
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
target        7
marital       0
education     0
dtype: int64

## Tratamento de Valores Ausentes

A próxima coluna que vamos tratar com valores ausentes é a do mês (month)

In [10]:
# Valores ausentes na variável
df.month.isnull().sum()

23

In [11]:
# Percentual de valores ausentes
df.month.isnull().mean()*100

0.05087257525823362

Como o percentual é menor que 30% não é indicada a deleção da coluna. 
Temos aqui também duas opções: 1) Eliminar os registros com valores ausentes (nesse caso perderíamos 23 linhas no dataset) ou 2) Aplicar imputação de dados.
Para este caso, vamos aqui também, fazer a imputação de dados.

In [12]:
# Tipo da variável
df.month.dtypes

dtype('O')

In [13]:
# Categorias da variável
df.month.value_counts()

month
may    13758
jul     6893
aug     6245
jun     5340
nov     3967
apr     2930
feb     2649
jan     1401
oct      738
sep      578
mar      475
dec      214
Name: count, dtype: int64

Ao analisarmos a distribuição e contagem dos meses registrados no dataset, percebemos que existe uma maior qtd de registros no mês de maio (may). Para que não haja mudança no padrão de distribuição dos dados no dataset, e por ser a quantidade de valores ausentes pequena, podemos fazer a imputação dos dados utilizando, aqui também, a moda.

In [14]:
# Vamos imputar com a moda, o valor mais frequente da variável, pois são poucos registros
df.month.mode()

0    may
Name: month, dtype: object

In [15]:
# Imputação com a moda
df.month.fillna("may", inplace = True)

In [16]:
# Valores ausentes tratados com sucesso
df.month.isnull().sum()

0

## Salvando os Dados desta Etapa 4

In [17]:
# Salvando os dados
df.to_csv('dados/bank-full_parte4.csv')

## Fim da Parte 4