![title](imagens/cabec_08g.jpg)

# <font color='green'>Projeto 6 - Marketing para Instituições Financeiras - Parte 07</font>
## <font color='green'>Tratamento de Valores Ausentes  - E</font>

## Carregando os Pacotes e o DataSet

In [1]:
# Importação dos Pacotes necessários para este projeto
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Carrega o dataset
df = pd.read_csv("dados/bank-full_parte6.csv")

In [3]:
# Shape
df.shape

(45204, 19)

In [4]:
# Amostra
df.head()

,Unnamed: 0,age,job,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,0,58,management,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,1,44,technician,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,2,33,entrepreneur,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,3,47,blue-collar,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,4,33,unknown,60000.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [5]:
# Como removemos o id, ao sarvar o arquivo, o pandas cria uma nova coluna de identificação e ele chama de Unnamed:0 
# Vamos removê-la.
df.drop(["Unnamed: 0"], axis = 1, inplace = True)

In [6]:
# Amostra
df.head()

,age,job,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,58,management,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,44,technician,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,33,entrepreneur,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,47,blue-collar,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,33,unknown,60000.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [7]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45204 entries, 0 to 45203
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45204 non-null  int64
 1   job        45204 non-null  object
 2   salary     45204 non-null  float64
 3   balance    45204 non-null  int64
 4   default    45204 non-null  object
 5   housing    45204 non-null  object
 6   loan       45204 non-null  object
 7   contact    45204 non-null  object
 8   day        45204 non-null  int64
 9   month      45204 non-null  object
 10  duration   45204 non-null  int64
 11  campaign   45204 non-null  int64
 12  pdays      45204 non-null  int64
 13  previous   45204 non-null  int64
 14  poutcome   45204 non-null  object
 15  target     45204 non-null  object
 16  marital    45204 non-null  object
 17  education  45204 non-null  object
dtypes: float64(1), int64(7), object(10)
memory usage: 6.2+ MB

In [8]:
# Temos valores nulos?
df.isna().any()

age          False
job          False
salary       False
balance      False
default      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
target       False
marital      False
education    False
dtype: bool

In [ ]:
# Temos valores nulos?
df.isna().sum()

## Tratamento de Valores Ausentes

Vamos analisar a coluna pdays (segundo a descrição no site que obtivemos o dataset, pdays (*past days*) indica o número de dias que se passaram desde que o cliente foi contatado pela última vez em uma campanha anterior (numérico; 999 significa que o cliente não foi contatado anteriormente).

In [9]:
# Valores ausentes
df.pdays.isnull().sum()

0

In [10]:
# Describe
df.pdays.describe()

count    45204.000000
mean        40.197836
std        100.128645
min         -1.000000
25%         -1.000000
50%         -1.000000
75%         -1.000000
max        871.000000
Name: pdays, dtype: float64

Segundo a descrição, uma vez contactado, registra-se a data... No próximo contato, se houver, neste campo será registrado o número de dias transcorridos.  Nesse caso... faz algum sentido o valor -1?
Portanto... para este caso em específico... -1 indica um valor ausente. Temos que tratá-lo.

In [11]:
# Vamos fazer relace de -1 por NaN
df.pdays = df.pdays.replace({-1.0:np.NaN})

In [12]:
# Valores ausentes
df.isnull().sum()

age              0
job              0
salary           0
balance          0
default          0
housing          0
loan             0
contact          0
day              0
month            0
duration         0
campaign         0
pdays        36948
previous         0
poutcome         0
target           0
marital          0
education        0
dtype: int64

In [13]:
# Calcula o percentual
df.pdays.isnull().mean()*100

81.73612954605787

Com essa constatação de que mais de 80% dos valores aqui estão "ausentes", qual a melhor alternativa?

ELIMINAR A COLUNA 'PDAYS', pois está acima de 30% de valores ausentes.

In [14]:
# Drop da coluna "pdays" 
df.drop(["pdays"], axis = 1, inplace = True)

In [15]:
# Valores ausentes
df.isnull().sum()

age          0
job          0
salary       0
balance      0
default      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
previous     0
poutcome     0
target       0
marital      0
education    0
dtype: int64

## Limpeza Concluída...

## Salvando os Dados Finais

In [16]:
# Salvando os dados
df.to_csv('dados/bank-full_final.csv')

## Fim da Parte 7