![title](imagens/cabec_09a.jpg)

## Transformação e Codificação de Variáveis...
## Mini-Projeto 8 - Count/Frequency Encoding

Vamos utilizar o dataset **"Mercedes-Benz Greener Manufacturing"** utilizado em uma competição do site **Kaggle**. Você pode ter acesso ao desafio completo e o dataset pelo seguinte endereço: https://www.kaggle.com/c/mercedes-benz-greener-manufacturing

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python usada neste Projeto no Jupyter Notebook:', python_version())

Versão da Linguagem Python usada neste Projeto no Jupyter Notebook: 3.11.7

In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote
# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada
# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Importação dos Pacotes (dupla dinâmica)
import pandas as pd
import numpy as np

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "pyPRO - Seja um Profissional Python!" --iversions

Author: pyPRO - Seja um Profissional Python!

numpy : 1.26.4
pandas: 2.2.2

In [5]:
# Mostrando todas as colunas do dataframe
pd.set_option('display.max_columns', None)

In [6]:
# Carregando os dados de algumas colunas específicas... no caso: X1, X2 e X3
df = pd.read_csv('dados/dataset.csv', usecols = ['X1','X2','X3'])

In [7]:
# Qual o formato deste dataframe carregado
df.shape

(4209, 3)

In [8]:
# Amostra dos dados (cabeçalho)
df.head()

  X1  X2 X3
0  v  at  a
1  t  av  e
2  w   n  c
3  t   n  f
4  v   n  f

In [9]:
# Mostrando os valores únicos dentro da coluna X1
len(df.X1.unique())

27

In [10]:
# Contando os valores únicos para cada uma das colunas
for i in df.columns:
    print(i,"-", len(df[i].unique()), "valores únicos ou categorias")

X1 - 27 valores únicos ou categorias
X2 - 44 valores únicos ou categorias
X3 - 7 valores únicos ou categorias

In [11]:
# Contagem/frequência das categorias da coluna X1
frequencia = df.X1.value_counts().to_dict()

In [12]:
# Vizualizando o dicionário que contem a frequência de cada categoria.
frequencia

{'aa': 833,
 's': 598,
 'b': 592,
 'l': 590,
 'v': 408,
 'r': 251,
 'i': 203,
 'a': 143,
 'c': 121,
 'o': 82,
 'w': 52,
 'z': 46,
 'u': 37,
 'e': 33,
 'm': 32,
 't': 31,
 'h': 29,
 'y': 23,
 'f': 23,
 'j': 22,
 'n': 19,
 'k': 17,
 'p': 9,
 'g': 6,
 'd': 3,
 'q': 3,
 'ab': 3}

In [13]:
# Vamos fazer o "replace" de cada categoria pela contagem/frequencia na coluna X1
df.X1 = df.X1.map(frequencia)

In [14]:
df

       X1  X2 X3
0     408  at  a
1      31  av  e
2      52   n  c
3      31   n  f
4     408   n  f
...   ...  .. ..
4204  598  as  c
4205   82   t  d
4206  408   r  a
4207  251   e  f
4208  251  ae  c

[4209 rows x 3 columns]

### Pare e faça o "replace" pela frequência nas demais colunas: X2 e X3

Importante que você tente fazer antes de ver os resultados abaixo. Praticar... fazer, ajuda no processo de fixação dos procedimentos.
Vamos ao processo...

In [15]:
# Contagem/frequencia das categorias da coluna X2
frequencia = df.X2.value_counts().to_dict()

In [16]:
# Agora fazemos o replace de cada categoria pela contagem/frequencia na coluna X2
df.X2 = df.X2.map(frequencia)

In [17]:
# Contagem/frequencia das categorias da coluna X3
frequencia = df.X3.value_counts().to_dict()

In [18]:
# Agora fazemos o replace de cada categoria pela contagem/frequencia na coluna X3
df.X3 = df.X3.map(frequencia)

In [ ]:
# Ao final, para validarmos o processo... verificamos se algum valor nulo foi gerado
df.isnull().any()

In [ ]:
# O processo foi concluído com Sucesso.
# Mostrando o DataFrame resultante...

df

## Fim do Mini-Projeto 8